### ISSUE TITLE
Addon not syncing watch history with AndriodTV version

### ISSUE THREAD

**Issue by SilentRocket** [SageTendo/mal-stremio-addon#24]
The AndroidTV version is able to pull my watch list from Mal, but when after watching the episode, it doesn't update on mal.

I checked with the Mobile version of Stremio and works with no issue.

**Comment by SilentRocket** [comment]
I don't get an error message at all. I select the subtitle, and I'm able to watch the episodes, but it just doesn't reflect on mal.

**Comment by SageTendo** [comment]
I've looked into Stremio documentation and the web version and Android TV are built on the new system. On web, it updates MAL, so it shouldn't be any different for TV. It will be hard for me to debug or try to see if I can fix this without an Android TV. I'll look at possible workarounds like emulating Android TV, but it will take quite some time to get around to it. Sorry for the inconvenience.

**Comment by SilentRocket** [comment]
No inconvenience caused. I thought I was missing something on my end, but it's still works on pc and phone so I'll use that for now. Thanks foe looking into it.

**Comment by SageTendo** [comment]
Hi, a little late but I've been playing around with the Android TV version of Stremio and it seems to update my watchlist. On the backend, every request that should be made from the TV is being made, so I'm not sure why it works on my TV but not on another (maybe it's TV model specific??). 

You could try setting the preferred subtitle language in the Stremio settings (I have mine set to English) and see if that resolves the issue. Otherwise, there's not much else I can think of at the moment to fix it.
